name: lint-wf
on:
  push:
   branches:
     -develop
  pull-request:
     -develop
jobs:
   linting-lates:
      runs-on:  ubuntu-latest
      steps:
        - name: Checkout Repositry
          uses: actions/checkout@v4
        - name: Install Html Hint
          run:  npm install --save-dev htmlhint
        - name: Install Style lint css
          run:  npm install --save-dev stylelint
        - name: lint html files
          run:  npx htmlhint "**/*.html"
        - name: Lint stylelint css files
          run:   npx stylelint "**/*.css"
        - name: LInt javascript
          run: npm install --save-dev eslint
        - name: lint js files
          run:  npx eslint "**/*.js"   
        - name: Dsipay package.json contents
          run:  cat package.json 

       
       
      
